// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydinwnddkyghzinwccba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkaW53bmRka3lnaHppbndjY2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNDAxNjksImV4cCI6MjA3NDgxNjE2OX0.Pl7zfqImZW8BOHZLHbzfWj0qa1POD4HfPX5--pi7gY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});