// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpklikbobbcgklnrgqzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wa2xpa2JvYmJjZ2tsbnJncXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODIwMDgsImV4cCI6MjA3NDY1ODAwOH0.X7k0vLBIjakLUJfJo12MSzE9-uX2yD3I4SLIkiBlfZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});